// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWkunsHLslsch1_B7gTPtmmwGEInv8qEo',
    appId: '1:150110765872:web:ff8e0cf056ce1858897ef5',
    messagingSenderId: '150110765872',
    projectId: 'fir-58ac8',
    authDomain: 'fir-58ac8.firebaseapp.com',
    storageBucket: 'fir-58ac8.appspot.com',
    measurementId: 'G-2J99Q7J8DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAti9m58BS62EyVHJoZIICMJAhdqRLqiiA',
    appId: '1:150110765872:android:403dba0d9fbd6483897ef5',
    messagingSenderId: '150110765872',
    projectId: 'fir-58ac8',
    storageBucket: 'fir-58ac8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogaipnKo4fGKa75qld9R2UV18VjZQeQ0',
    appId: '1:150110765872:ios:e0f6fe61b93e7dda897ef5',
    messagingSenderId: '150110765872',
    projectId: 'fir-58ac8',
    storageBucket: 'fir-58ac8.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogaipnKo4fGKa75qld9R2UV18VjZQeQ0',
    appId: '1:150110765872:ios:e0f6fe61b93e7dda897ef5',
    messagingSenderId: '150110765872',
    projectId: 'fir-58ac8',
    storageBucket: 'fir-58ac8.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWkunsHLslsch1_B7gTPtmmwGEInv8qEo',
    appId: '1:150110765872:web:1601dd309b8d5c92897ef5',
    messagingSenderId: '150110765872',
    projectId: 'fir-58ac8',
    authDomain: 'fir-58ac8.firebaseapp.com',
    storageBucket: 'fir-58ac8.appspot.com',
    measurementId: 'G-KC45GYZZ5Z',
  );
}
